"""initial schema

Revision ID: 76a40d5ae940
Revises: 
Create Date: 2026-08-17 12:34:19.979287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a40d5ae940'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('comment_id', sa.String(length=255), nullable=True),
    sa.Column('post_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_events_comment_id', 'events', ['comment_id'], unique=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_processed', 'events', ['processed'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('dm_message', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rules_active', 'rules', ['active'], unique=False)
    op.create_index('ix_rules_keyword', 'rules', ['keyword'], unique=False)
    op.create_table('dm_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('comment_id', sa.String(length=255), nullable=True),
    sa.Column('recipient_user_id', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sending', 'accepted', 'retrying', 'delivered', 'failed', 'cancelled', name='dm_job_status', native_enum=False, length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('dm_id', sa.String(length=255), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'recipient_user_id', name='uq_dm_jobs_rule_recipient')
    )
    op.create_index('ix_dm_jobs_event_id', 'dm_jobs', ['event_id'], unique=False)
    op.create_index('ix_dm_jobs_next_retry_at', 'dm_jobs', ['next_retry_at'], unique=False)
    op.create_index('ix_dm_jobs_recipient_user_id', 'dm_jobs', ['recipient_user_id'], unique=False)
    op.create_index('ix_dm_jobs_rule_id', 'dm_jobs', ['rule_id'], unique=False)
    op.create_index('ix_dm_jobs_status', 'dm_jobs', ['status'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dm_job_id', sa.Uuid(), nullable=False),
    sa.Column('dm_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('queued', 'delivered', 'failed', name='delivery_status', native_enum=False, length=20), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=255), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dm_job_id'], ['dm_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dm_job_id')
    )
    op.create_index('ix_deliveries_dm_id', 'deliveries', ['dm_id'], unique=False)
    op.create_index('ix_deliveries_recipient_user_id', 'deliveries', ['recipient_user_id'], unique=False)
    op.create_index('ix_deliveries_status', 'deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deliveries_status', table_name='deliveries')
    op.drop_index('ix_deliveries_recipient_user_id', table_name='deliveries')
    op.drop_index('ix_deliveries_dm_id', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index('ix_dm_jobs_status', table_name='dm_jobs')
    op.drop_index('ix_dm_jobs_rule_id', table_name='dm_jobs')
    op.drop_index('ix_dm_jobs_recipient_user_id', table_name='dm_jobs')
    op.drop_index('ix_dm_jobs_next_retry_at', table_name='dm_jobs')
    op.drop_index('ix_dm_jobs_event_id', table_name='dm_jobs')
    op.drop_table('dm_jobs')
    op.drop_index('ix_rules_keyword', table_name='rules')
    op.drop_index('ix_rules_active', table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_events_processed', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_index('ix_events_comment_id', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
